### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by SkyShiS** [CN-UPB/NFVdeep#1]
Hello! This is a great program and I download it, but it misses "request.json". Can you share the file with me? My Email address is shishang@bupt.edu.cn. Thank you very much for your consideration. I am very pleased to hear from you.

Yours sincerely

**Comment by stefanbschneider** [comment]
Hi, `requests.json` configures the kind of traffic/requests you want to simulate. 

As example requests, see the ones in the results directory, eg, https://github.com/CN-UPB/NFVdeep/blob/main/results/abilene/static/default/requests.json

Or in the data directory.

Does this help?

**Comment by SkyShiS** [comment]
On, I see the file. Thanks for help!

**Comment by SkyShiS** [comment]
Hello! I get a question that I have already installed tensorflow-gpu2.2.0 and cuda, but when I run the script.py, it said "Using cpu device". How do I set up gpu device to run the program?

Yours sincerely

**Comment by stefanbschneider** [comment]
We only tested our NFVdeep installation on CPU, not GPU. So I'm not sure if I can help here.

Either way, my understading is that the reinforcement learning part uses [`stable-baselines3`](https://stable-baselines3.readthedocs.io/en/master/index.html), which in turn builds on PyTorch, not TensorFlow.
Not sure why we have the TF dependency. @NilsLuca @stwerner97 Do you know?

**Comment by stweigand97** [comment]
Hi :) As @stefanbschneider mentioned, we primarily used the CPU installation of `PyTorch` for `stable-baselines3`.  The TF dependencies could either be deprecated since we migrated from `stable-baselines` (Tensorflow) to `stable-baselines3` (PyTorch) during development. Also, we used `TensorBoard` for monitoring and testing which requires an installation of TF (as far as I am aware of it).

**Comment by SkyShiS** [comment]
Hi, thanks for answering! I have already installed the environment and successfully run the program. You have done a wonderful job! For further study, I want to learn more about what the differences between static and dynamic in requests.json are. And I want to learn about the Abilene network topology. Is there any introductions or graphs about abilene.gpickle? Thanks!

**Comment by stefanbschneider** [comment]
Thanks! The Abilene network topology is from [Topology Zoo](http://topology-zoo.org/). There's more documentation on their website. You'll also find more information about Abilene in general on Google or [Wikipedia](https://en.wikipedia.org/wiki/Abilene_Network).

Regarding `static/dynamic` in `requests.json`, I think it has to do something with how the requests are generated, but I'm not sure about the details. @stwerner97 @NilsLuca Maybe put a short documentation/description of all fields in `requests.json` into the Readme?
