### ISSUE TITLE
How to use the  experiment  to  make the figures?

### ISSUE THREAD

**Issue by w1w9** [CN-UPB/NFVdeep#10]
Hello  sir, it is my honor to study  your project. I  can understand   the rough process, but I do not  know   how  to  use  the  experiment  results  and  use them to make the figures like  that. Could  you  give  me  an instruction  about  the  experimental indicators ?(logs, placements in script.py and  ray results in tuning.py). I  am  looking forward to your reply very much.
![image](https://user-images.githubusercontent.com/89134306/232060734-53df4c34-88d9-4957-bc20-03df0fee335e.png)
![image](https://user-images.githubusercontent.com/89134306/232060889-7dc807e4-0a18-456a-bef9-29fa833df743.png)
![image](https://user-images.githubusercontent.com/89134306/232060946-2ba447d2-ff51-458c-931b-459bf76936be.png)

**Comment by 17719108990** [comment]
> Hello sir, it is my honor to study your project. I can understand the rough process, but I do not know how to use the experiment results and use them to make the figures like that. Could you give me an instruction about the experimental indicators ?(logs, placements in script.py and ray results in tuning.py). I am looking forward to your reply very much. ![image](https://user-images.githubusercontent.com/89134306/232060734-53df4c34-88d9-4957-bc20-03df0fee335e.png) ![image](https://user-images.githubusercontent.com/89134306/232060889-7dc807e4-0a18-456a-bef9-29fa833df743.png) ![image](https://user-images.githubusercontent.com/89134306/232060946-2ba447d2-ff51-458c-931b-459bf76936be.png)

Hello, could you share this code with me for learning? Thank you!

**Comment by stefanbschneider** [comment]
I'm happy you are working with our project! Sorry for the late reponse.

@stwerner97 @NilsLuca Does one of you remember in which format the results were stored and could share some tips about how to plot them?

**Comment by stweigand97** [comment]
Yes, sure, sorry for the late response!

Looking at the [EvalLogCallback](https://github.com/CN-UPB/NFVdeep/blob/main/nfvdeep/environment/monitor.py), we store statistics about ``Eval. Iter``, ``Episode``, ``Arrival``, ``TTL``, ``Bandwidth``, ``Max Latency``, ``VNFs``, and ``Placements`` at each step(?) of the simulation. The ``VNFs`` field is a list that denotes the components of the ``SFC`` and their resource requirements (cpu & memory). 

In terms of plotting our results, I just collected the statistics of each episode in a pandas dataframe, aggregated the data (e.g., computed the average total reward of episodes) and visualized them using [seaborn](https://seaborn.pydata.org/) & [matplotlib](https://matplotlib.org/).

**Comment by w1w9** [comment]
Thank you,sir.You&nbsp; are&nbsp; very&nbsp; friendily.It's&nbsp; my&nbsp; hornor&nbsp; to&nbsp; study&nbsp; your project.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CN-UPB/NFVdeep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 凌晨3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CN-UPB/NFVdeep] How to use the  experiment  to  make the figures? (Issue #10)





 
Closed #10 as completed.
