### ISSUE TITLE
I need some help to learn this project

### ISSUE THREAD

**Issue by Desperado6** [CN-UPB/NFVdeep#11]
Hello sir, it is my honor to study your project. 
When I run the program, in the [_on_step()] function of EvalLogCallback, 
`eval_ Envs: List [StatsWrapper]=self. local ["callback"]. eval_ Env. envs`
This line of code shows that there is no "callback" variable name . I want to know if the monitor file is missing any content.
I am looking forward to your reply very much.

**Comment by pengxiaoywan** [comment]
Expected type 'Union[Env, VecEnv]', got 'StatsWrapper' instead ,how to fix it
