### ISSUE TITLE
Error running tune.py 

### ISSUE THREAD

**Issue by Rabipour** [CN-UPB/NFVdeep#4]
Hi
I ran the first part of NFVDeep successfully (Experiments/script.py).
But in executing the second part(Hyperparameter Optimization/tune.py) , I encounter the following error:

  _File "C:\Users\98913\Documents\Python\NFVdeep-main\tune.py", line 158, in <module>
    search_alg=AxSearch(ax_client),
  File "C:\Simulate\lib\site-packages\ray\tune\suggest\ax.py", line 173, in __init__
    self._setup_experiment()
  File "C:\Simulate\lib\site-packages\ray\tune\suggest\ax.py", line 197, in _setup_experiment
    raise ValueError(
ValueError: Please specify the `mode` argument when initializing the `AxSearch` object or pass it to `tune.run()`._

I spent many hours fixing it but did not get the result.Please help me fix this error.

**Comment by stefanbschneider** [comment]
The error message ("or pass it to tune.run()") doesn't really make sense to me since you do pass it to `tune.run()` in the corresponding line if you didn't change the `tune.py` script.

Either way, you could try setting `mode="max"` as extra argument inside the `AxSearch` constructor. Not sure if this will work. Let me know.

**Comment by Rabipour** [comment]
> The error message ("or pass it to tune.run()") doesn't really make sense to me since you do pass it to `tune.run()` in the corresponding line if you didn't change the `tune.py` script.
> 
> Either way, you could try setting `mode="max"` as extra argument inside the `AxSearch` constructor. Not sure if this will work. Let me know.

I did what you said first (mode="max" inside the AxSearch) ,but it made the same error again.
The error was related to requirements and was fixed. 
Thanks

**Comment by Rabipour** [comment]
Can the number of nodes be changed for each experiment? If so, where should it be done?
Please help me

**Comment by stefanbschneider** [comment]
Do you mean nodes of the underlying computer network topology? You need to define the network topology in a separate file. There are examples here: https://github.com/CN-UPB/NFVdeep/tree/main/data
You can then pass the network file as input when you run the algorithm.

But keep in mind that this is not an official implementation of NFVdeep and that we could not reproduce the results of the paper. Just so you know before you invest too much time.

**Comment by Rabipour** [comment]
> Do you mean nodes of the underlying computer network topology? You need to define the network topology in a separate file. There are examples here: https://github.com/CN-UPB/NFVdeep/tree/main/data You can then pass the network file as input when you run the algorithm.
> 
> But keep in mind that this is not an official implementation of NFVdeep and that we could not reproduce the results of the paper. Just so you know before you invest too much time.

Yes, "nodes of the underlying computer network topology"
I realized, Thanks

**Comment by Lundon3344567** [comment]
> > The error message ("or pass it to tune.run()") doesn't really make sense to me since you do pass it to `tune.run()` in the corresponding line if you didn't change the `tune.py` script.
> > Either way, you could try setting `mode="max"` as extra argument inside the `AxSearch` constructor. Not sure if this will work. Let me know.
> 
> I did what you said first (mode="max" inside the AxSearch) ,but it made the same error again. The error was related to requirements and was fixed. Thanks
I also did this. But an error message "TypeError: 'AxClient' object is not iterable" came. Please tell me how you deal with it? Or can you give me some other advice?

**Comment by Lundon3344567** [comment]
ValueError: Please specify the `mode` argument when initializing the `AxSearch` object or pass it to `tune.TuneConfig()`.
Try to replace it with the following code 

`ray.tune.run(
            evaluate_objective,
            num_samples=RAY_TUNE_SAMPLES,
            search_alg=AxSearch(ax_client=ax_client),
            scheduler=asha_scheduler,
            verbose=2
     )`
