### ISSUE TITLE
You forgot the file environment.yml

### ISSUE THREAD

**Issue by ZhangQuan-hub** [CN-UPB/NFVdeep#8]
Thank you for your sharing ,but you forgot to export the package version to the environment.yml.So  there is no environment.yml found.

**Comment by stefanbschneider** [comment]
Hi @Mokkeey , true, there is no `environment.yml`. Does the setup work with `python setup.py install` or `pip install .`? For development with `pip install -e .`

If so, I can update the setup instructions in the readme.
